volumes:
  mysql-data:

services:
  app-dev:
    image: r0x16/crodont:1.0.0
    # working_dir value has to be the same of mapped volume
    ports:
      - 8081:80
    volumes:
      - ./project/:/var/lib/crodont
    environment:
      - GROUND_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=crodont
  # Mariadb service
  db:
    image: mariadb:10.9
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crodont